"""Deterministic TEXT entity ↔ GRAPHIC entity bridge."""

from .entity_bridge import (
    BridgeValidationError,
    build_entity_links,
    build_entity_links_from_artifacts,
    entity_links_are_stale,
    graphic_entities_from_system_graph,
    validate_entity_links,
    validate_entity_links_artifact,
)
from .document_binding import (
    BINDING_AMBIGUOUS,
    BINDING_ERROR,
    BINDING_MISMATCH,
    BINDING_PROVEN,
    BINDING_STATES,
    BINDING_UNPROVEN,
    DocumentBindingValidationError,
    compare_document_identity,
    document_descriptor_for_block,
    document_identity_is_complete,
    normalize_document_descriptor,
    normalize_pair_documents,
    pair_documents_from_pair_artifact,
    validate_document_binding,
    verify_document_binding,
)
from .graph_entity_adapter import build_graph_entities, validate_graph_entities
from .parent_page_relation import (
    ParentPageRelationValidationError,
    RELATION_AMBIGUOUS,
    RELATION_MISMATCH,
    RELATION_PROVEN,
    RELATION_STATES,
    RELATION_UNPROVEN,
    RELATION_VERSION,
    make_parent_page_relation,
    normalize_parent_page_relations,
    validate_parent_page_relation,
)
from .comparison_scope import (
    build_scope_join,
    normalize_graphic_scope_groups,
    produce_graphic_scope_groups,
    query_text_scope,
    validate_scope_join,
)
from .entity_normalizer import normalize_entity_name, normalize_functional_role
from .graphic_coverage import (
    build_graphic_coverage,
    coverage,
    saved_coverage_bundle_is_stale,
    validate_graphic_coverage,
)
from .side_entity_contract import (
    build_side_entity_links,
    build_side_graph_entities,
    query_text_entity_side,
    validate_side_entity_links,
    validate_side_graph_entities,
)
from .text_entity_producer import build_text_entities, validate_text_entities

__all__ = [
    "BINDING_AMBIGUOUS",
    "BINDING_ERROR",
    "BINDING_MISMATCH",
    "BINDING_PROVEN",
    "BINDING_STATES",
    "BINDING_UNPROVEN",
    "BridgeValidationError",
    "DocumentBindingValidationError",
    "ParentPageRelationValidationError",
    "RELATION_AMBIGUOUS",
    "RELATION_MISMATCH",
    "RELATION_PROVEN",
    "RELATION_STATES",
    "RELATION_UNPROVEN",
    "RELATION_VERSION",
    "build_entity_links",
    "build_entity_links_from_artifacts",
    "build_graph_entities",
    "build_graphic_coverage",
    "build_scope_join",
    "build_side_entity_links",
    "build_side_graph_entities",
    "build_text_entities",
    "coverage",
    "compare_document_identity",
    "document_descriptor_for_block",
    "document_identity_is_complete",
    "entity_links_are_stale",
    "graphic_entities_from_system_graph",
    "make_parent_page_relation",
    "normalize_document_descriptor",
    "normalize_entity_name",
    "normalize_graphic_scope_groups",
    "normalize_functional_role",
    "normalize_pair_documents",
    "normalize_parent_page_relations",
    "pair_documents_from_pair_artifact",
    "produce_graphic_scope_groups",
    "query_text_entity_side",
    "query_text_scope",
    "saved_coverage_bundle_is_stale",
    "validate_document_binding",
    "validate_entity_links",
    "validate_entity_links_artifact",
    "validate_graph_entities",
    "validate_graphic_coverage",
    "validate_parent_page_relation",
    "validate_scope_join",
    "validate_side_entity_links",
    "validate_side_graph_entities",
    "validate_text_entities",
    "verify_document_binding",
]
